chore(npm) : Prettier Install and build environment
yanachuwan9sm/own-fm pull request #11
Opened 2022-12-05 13:36 UTC by yanachuwan9sm

close #5

2022-12-05 13:39 UTC, yanachuwan9sm commented
[申し送り] 
- .prettierignore は [公式](https://github.com/vercel/next.js/blob/canary/.prettierignore) のものをそのまま使用
-  prettierの設定はファイル数をできる限り削減するため、`package.json` に記載

2022-12-05 14:50 UTC, piro0919 commented
@yanachuwan9sm 

[must]

.prettierignore の参考元については、next の公式であって Next.js のサイト用に最適化されたものでないので、参考にするにはちょっと微妙かなーと思いました。 👀 
現状は作成不要な気もしますが、いかがでしょうか。

2022-12-05 14:52 UTC, piro0919 commented
@yanachuwan9sm 

[imo]

> prettierの設定はファイル数をできる限り削減するため、package.json に記載

これが結構微妙なラインで、最近はむしろ package.json の記載内容をシンプルにするためにファイルを分割するほうがメジャーな印象があります。
個人的にも、ファイル数が増えても各ファイルごとの目的が明確な方が好ましいと最近は思っていますが、どうでしょうか。
これについては答えがあるわけではないので、今のままでも問題ないです。 👍

2022-12-05 14:59 UTC, piro0919 requested changes

2022-12-05 14:59 UTC, piro0919 commented on package.json
> +    "format": "prettier --write --ignore-path .gitignore './**/*.{ts,tsx,json,css}'"
[imo]

フォーマットをかけるファイルを `ts,tsx,json,css` で制限した理由ってなんでしょうか。 👀 
個人的には特に制限しなくても良いかなーと思いますが、どうでしょうか。

2022-12-05 14:59 UTC, piro0919 commented on package.json
> +    "printWidth": 80
[imo]

ここの設定ってどうやって決められましたでしょうか。
個人的に Prettier はデフォルトの設定派なので、単純に気になりました。 😺

2022-12-05 14:59 UTC, piro0919 commented on package.json
> +    "prettier": "^2.8.0"
[must]

バージョンは固定してインストールしましょう！
そのため、本来であれば `.npmrc` ファイルの作成を優先したほうが良かったかもですね。 😃 

rel https://github.com/yanachuwan9sm/own-fm/issues/9

2022-12-05 14:59 UTC, piro0919 commented on package.json
> +    "prettier": "^2.8.0"
[nits]

Next.js の v13 からパッケージはすべて dependencies に集約されるようになりましたが、どうでしょうか。
ちなみに個人的には今のままでもどっちでも良いかなーと思います。

2022-12-06 04:41 UTC, yanachuwan9sm commented
ご確認頂き有難う御座います🙏

> .prettierignore の参考元については、next の公式であって Next.js のサイト用に最適化されたものでないので、参考にするにはちょっと微妙かなーと思いました。 👀

なるほどですね、、有難う御座います！
ご指摘の通り、現状は作成不要かな〜と思いますので削除いたします。

> 最近はむしろ package.json の記載内容をシンプルにするためにファイルを分割するほうがメジャーな印象があります。

そうなのですね！あまり現場における動向を理解していないので助かります🙇‍♂️
確かにファイル数を減らすよりも、以下の方がメリットが多いような気がします🤔
package.json の記載内容をシンプルにする & 各ファイルごとの目的が明確 

こちらも、 package.json ではなく別途ファイル作成致します👍

2022-12-06 07:14 UTC, yanachuwan9sm commented on package.json
> +    "prettier": "^2.8.0"
@piro0919 

自分も、`create-next-app` で生成したプロジェクトのパッケージが全て dependencies に集約されていて、疑問に思っていたのですがそのような経緯があったのですね！勉強になります🙏

>Next.js の v13 からパッケージはすべて dependencies に集約されるようになりました

この部分如何する記述って以下で合っていますか？？
(公式Docsで探してみたのですが、なかなかそこに関する記述が見つけられず、、)
https://beta.nextjs.org/docs/upgrade-guide/version-12#:~:text=During%20next%20build%2C%20Next.js%20will%20automatically%20trace%20each%20page%20and%20its%20dependencies%20to%20determine%20all%20of%20the%20files%20that%20are%20needed%20for%20deploying%20a%20production%20version%20of%20your%20application.

2022-12-06 07:30 UTC, yanachuwan9sm commented on package.json
> +    "printWidth": 80
@piro0919 
デフォルトの値とは異なるオプション semi、singleQuote、jsxSingleQuote は
いつも true で使うことが多いため、trueにした感じです！(適当な理由ですいません🙏)
(その他はデフォルトの値のままなので削除しても問題ないですね)

2022-12-06 07:39 UTC, yanachuwan9sm commented on package.json
> +    "format": "prettier --write --ignore-path .gitignore './**/*.{ts,tsx,json,css}'"
> フォーマットをかけるファイルを ts,tsx,json,css で制限した理由ってなんでしょうか。
制限したファイル以外使わないかなと思い制限しました。
そもそもスタイリング周りも何を使うか決めていないので現時点で制限を行う必要はないと思いました。
また、制限した理由も曖昧であるため、特段制限しないように修正致します！

2022-12-06 10:33 UTC, yanachuwan9sm commented on package.json
> +    "format": "prettier --write --ignore-path .gitignore './**/*.{ts,tsx,json,css}'"
こちらのコミットにて修正致しました！

fa33cd3e5f4f46f8b82031ec690d3aba7cedfb40

2022-12-06 10:34 UTC, yanachuwan9sm commented on package.json
> +    "printWidth": 80
こちらの方、`package.json` に記述するのではなく、
新しく `.prettierrc` を作成し、設定し直しました🙏

fa33cd3e5f4f46f8b82031ec690d3aba7cedfb40

2022-12-06 10:35 UTC, yanachuwan9sm commented on package.json
> +    "prettier": "^2.8.0"
バージョンを固定してインストールし直しました。
(優先的に `.npmrc`  ファイルの作成の issue から取り掛かります👍)

1e63045ff0bb0fc679fddeaad737eaba4914e412

2022-12-06 13:15 UTC, piro0919 approved these changes
LGTM 👍

2022-12-06 13:49 UTC, merged