feat: :sparkles: implement a blog post listing page
yanachuwan9sm/own-fm pull request #69
Opened 2023-03-07 14:21 UTC by yanachuwan9sm

close #66

2023-03-07 14:23 UTC, yanachuwan9sm commented
ビルド時に page.tsx が Static として生成されているものを確認できた。

```
Route (app)                                Size     First Load JS
─ ○ /                                      5.64 kB        73.4 kB
+ First Load JS shared by all              67.8 kB
  ├ chunks/701-dca222a8896a4571.js         65.5 kB
  ├ chunks/main-app-15244521dd7e6111.js    203 B
  └ chunks/webpack-69afa2f3f2c96437.js     2.06 kB
```

2023-03-07 14:30 UTC, yanachuwan9sm commented on next.config.js
> +    // typedRoutes: true,
[申し送り]
experimental.typedRoutesを有効している状態だと、
`next dev` をおこなっても、ローカルサーバーが起動しませんでした。

以下のPRで削除した差分が関係していそうです。
ただし、ローカルのパスが差分に出ちゃうのはあまり良い気がしない & 現在beta版であることから今回は設定をオフに変更します。

https://github.com/yanachuwan9sm/own-fm/pull/65#discussion_r1121721770

公式Docs
https://beta.nextjs.org/docs/configuring/typescript#statically-typed-links:~:text=next%20dev%E3%81%BE%E3%81%9F%E3%81%AFnext%20build%E3%82%92%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B%E3%81%A8%E3%80%81Next.js%E3%81%AF%E3%80%81%E3%82%A2%E3%83%97%E3%83%AA%E3%82%B1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AB%E5%AD%98%E5%9C%A8%E3%81%99%E3%82%8B%E3%81%99%E3%81%B9%E3%81%A6%E3%81%AE%E3%83%AB%E3%83%BC%E3%83%88%EF%BC%88href%E3%82%BF%E3%82%A4%E3%83%97%E3%81%8CLink%E3%81%A7%E3%81%82%E3%82%8B%E6%9C%89%E5%8A%B9%E3%81%AA%E3%83%AB%E3%83%BC%E3%83%88%E3%81%99%E3%81%B9%E3%81%A6%EF%BC%89%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E6%83%85%E5%A0%B1%E3%82%92%E5%90%AB%E3%82%80.next%E5%86%85%E3%81%AE%E9%9A%A0%E3%81%97.d.ts%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E7%94%9F%E6%88%90%E3%81%97%E3%81%BE%E3%81%99%E3%80%82%E3%81%93%E3%81%AE.d.ts%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AFtsconfig.json%E3%81%AB%E5%90%AB%E3%81%BE%E3%82%8C%E3%80%81TypeScript%E3%82%B3%E3%83%B3%E3%83%91%E3%82%A4%E3%83%A9%E3%81%8C%E3%81%93%E3%81%AE.d.ts%E3%82%92%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%81%97%E3%81%A6%E3%80%81%E7%84%A1%E5%8A%B9%E3%81%AA%E3%83%AA%E3%83%B3%E3%82%AF%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BF%E3%81%A7%E3%83%95%E3%82%A3%E3%83%BC%E3%83%89%E3%83%90%E3%83%83%E3%82%AF%E3%82%92%E6%8F%90%E4%BE%9B%E3%81%97%E3%81%BE%E3%81%99%E3%80%82

2023-03-07 14:41 UTC, piro0919 requested changes
結構厳し目ですが。 😺

2023-03-07 14:41 UTC, piro0919 commented on src/app/page.tsx
> +            <>
[imo]

Fragment いらないですね。 👀

2023-03-07 14:41 UTC, piro0919 commented on src/app/page.tsx
> +                      ({ fields }: Contentful.ITag) => fields.title
[imo]

引数に型与える必要ありましたっけ？
ちゃんと型が当たってないようにも見えますね。 👀

2023-03-07 14:41 UTC, piro0919 commented on src/libs/contentful.ts
> +  Pick<contentful.Sys, 'id' | 'createdAt' | 'updatedAt'>
[imo]

型がイマイチですね。
`EntryCollection` まで当てたほうが自然かと。

2023-03-07 14:41 UTC, piro0919 commented on src/libs/contentful.ts
> +  Pick<contentful.Sys, 'id' | 'createdAt' | 'updatedAt'>
[imo]

型が正しくないような？ 👀 
Pick した値以外って返してないんでしたっけ？

2023-03-07 14:41 UTC, piro0919 commented on src/libs/contentful.ts
> +    order: '-sys.createdAt',
[nits]

`order` はパラメーターで渡したほうが拡張性が高い気がしなくもないです。

2023-03-07 14:41 UTC, piro0919 commented on src/libs/contentful.ts
> +export const getBlogPosts = async (): Promise<
[imo]

export default で統一しないんでしたっけ？ 👀

2023-03-07 14:41 UTC, piro0919 commented on src/libs/contentful.ts
> +export const getBlogPosts = async (): Promise<
[imo]

libs 以下にこの実装を置くのは違和感ありますねー。
next の公式通り、普通に page コンポーネントに書いてやっても良い気がしますねー。

https://beta.nextjs.org/docs/data-fetching/fetching#asyncawait-in-server-components

2023-03-07 14:41 UTC, piro0919 commented on src/app/page.tsx
> +      createdAt: new Date(createdAt).toLocaleDateString(),
[imo]

素の Date 型は使い勝手が悪いので外部パッケージを使ったほうが良い気はしますね。
date-fns か dayjs あたりを使用するのはどうでしょうかー。

2023-03-07 14:41 UTC, piro0919 commented on src/app/page.tsx
> +        <p>BlogPosts</p>
[imo]

全体的に p タグの使い方がイマイチですね。 🙅‍♂️ 
普通に div で良いかなと。

2023-03-07 14:42 UTC, piro0919 commented
[must]

あとブランチ名がイマイチですね。 🙅‍♂️ 
基本的には小文字のハイフンつなぎで作成しましょうー。

2023-03-08 15:38 UTC, yanachuwan9sm commented on src/libs/contentful.ts
> +export const getBlogPosts = async (): Promise<
@piro0919 

ここは特段方針決めてなかったかもです、、！

export default 統一する場合って、
今回のように、汎用的な関数群をまとめた `libs`フォルダ配下の named export もアウトなんでしょうか？

> デフォルトと名前付きエクスポートの潜在的な混乱を減らすために、チームによっては、1つのスタイル（デフォルトまたは名前付き）だけにこだわったり、1つのファイルでそれらを混在させないことを選択したりします。これは好みの問題です。自分にとって最適な方法を選んでください
https://beta.reactjs.org/learn/importing-and-exporting-components#default-vs-named-exports

2023-03-09 00:35 UTC, yanachuwan9sm commented on src/libs/contentful.ts
> +  Pick<contentful.Sys, 'id' | 'createdAt' | 'updatedAt'>
@piro0919 

ご指摘有難うございます！

いずれは page.tsxをtemplateに切り出して、更にコンポーネント分けていくようにしようかな〜と思っていたので、
子コンポーネントに渡すPropsの型定義を `BlogPost` にて行ったのですが、
確かに、`EntryCollection` まで当てた方が良きですね、、
(今のままだと、子コンポーネントでページネーション実装しようと思っても出来ないですね、、)

Sysとfieldsだけ欲しい場合:
`type Props = contentful.Entry<Contentful.IBlogPostFields>[];`
そうでもない場合:
`type Props = contentful.EntryCollection<Contentful.IBlogPostFields>`
とかで問題ない気がしてきましたmm

2023-03-09 00:37 UTC, yanachuwan9sm commented on src/libs/contentful.ts
> +  Pick<contentful.Sys, 'id' | 'createdAt' | 'updatedAt'>
この画面ではPickした値のみしか使っていなかったので、
Pick使っていたのですが、上記同様、イマイチな実装だな〜と思いましたので、
修正致しますmm

2023-03-09 00:37 UTC, yanachuwan9sm commented on src/libs/contentful.ts
> +  Pick<contentful.Sys, 'id' | 'createdAt' | 'updatedAt'>
この画面ではPickした値のみしか使っていなかったので、
Pick使っていたのですが、上記同様、イマイチな実装だな〜と思いましたので、
修正致しますmm

2023-03-09 01:06 UTC, yanachuwan9sm commented on src/app/page.tsx
> +            <>
ご確認有難うございますmm

以下にて修正行いました！
f21dbc4c6fd060e6c2582589e802c705d1dacf7b

2023-03-09 01:07 UTC, yanachuwan9sm commented on src/app/page.tsx
> +                      ({ fields }: Contentful.ITag) => fields.title
ご確認有難うございますmm

確かに、引数に型を与える必要はないのかなと思いましたので、修正しました！
f21dbc4c6fd060e6c2582589e802c705d1dacf7b

2023-03-09 01:12 UTC, yanachuwan9sm commented on src/libs/contentful.ts
> +  Pick<contentful.Sys, 'id' | 'createdAt' | 'updatedAt'>
こちら、一旦今回はPorpsを渡すコンポーネントもないので、型定義は削除しましたmm

2023-03-09 01:13 UTC, yanachuwan9sm commented on src/libs/contentful.ts
> +  Pick<contentful.Sys, 'id' | 'createdAt' | 'updatedAt'>
上記に同様ですmm

https://github.com/yanachuwan9sm/own-fm/pull/69#discussion_r1130259727

2023-03-09 01:13 UTC, yanachuwan9sm commented on src/libs/contentful.ts
> +export const getBlogPosts = async (): Promise<
ご確認有難うございますmm

以下にて修正行いました！
https://github.com/yanachuwan9sm/own-fm/commit/f21dbc4c6fd060e6c2582589e802c705d1dacf7b

2023-03-09 01:14 UTC, yanachuwan9sm commented on src/app/page.tsx
> +        <p>BlogPosts</p>
軽く取得した情報を画面反映できればいいぐらいでマークアップしてたので、
少し修正しましたmm

https://github.com/yanachuwan9sm/own-fm/commit/f21dbc4c6fd060e6c2582589e802c705d1dacf7b

2023-03-09 01:16 UTC, yanachuwan9sm commented on src/app/page.tsx
> +      createdAt: new Date(createdAt).toLocaleDateString(),
>date-fns か dayjs あたりを使用するのはどうでしょうかー。

開発が活発そう(?) ＆ TypeScript で開発されている事から、 date-fns を採用しました！
また、素の Date型にて処理をしていた部分を date-fns を用いた実装に修正しましたmm

https://github.com/yanachuwan9sm/own-fm/commit/f21dbc4c6fd060e6c2582589e802c705d1dacf7b

2023-03-09 01:17 UTC, yanachuwan9sm commented on src/libs/contentful.ts
> +    order: '-sys.createdAt',
あんまり指摘内容が理解できていないかもです、、、！

2023-03-09 04:01 UTC, piro0919 commented on src/libs/contentful.ts
> +export const getBlogPosts = async (): Promise<
@yanachuwan9sm 

統一のルールについてはおまかせしますー。
ただ個人的には汎用的なファイルって作成する必要がないと思いますね。
汎用的なファイルを作るくらいなら、1 つ 1 つのファイルを厳密にしたほうが、結果的に保守性は高くなるかなと。

2023-03-09 04:03 UTC, piro0919 commented
@yanachuwan9sm 

[f21dbc4](https://github.com/yanachuwan9sm/own-fm/pull/69/commits/f21dbc4c6fd060e6c2582589e802c705d1dacf7b) このコミット良くないですね。 🙅‍♂️ 
あとから振り返ったときにコミットの内容がすぐに理解できるような粒度かつコミットメッセージを打つように心がけましょうー。

2023-03-09 04:03 UTC, piro0919 commented
@yanachuwan9sm

[f21dbc4](https://github.com/yanachuwan9sm/own-fm/pull/69/commits/f21dbc4c6fd060e6c2582589e802c705d1dacf7b) あとコミットメッセージも良くないですね。 🙅‍♂️ 
コミットメッセージは動詞から始めましょうー。

2023-03-09 04:10 UTC, piro0919 requested changes

2023-03-09 04:10 UTC, piro0919 commented on src/app/page.tsx
> +  //* MEMO: 子コンポーネントにPropsを渡す際は、postDateを渡す
[must]

別にそんな決まりはないような。 👀 
ケースバイケースだと思います。

2023-03-09 04:10 UTC, piro0919 commented on src/app/page.tsx
> +  })
[must]

書きっぷりがかなりイマイチですね。 👀 

```tsx
const postList = postDate.items.map(({fields, sys: {id, createdAt, updatedAt}}) => ({
      // 展開は最初にやりましょう！
      ...fields,
      id,
      createdAt: format(new Date(createdAt), 'MMM dd,yyyy'),
      updatedAt: format(new Date(updatedAt), 'MMM dd,yyyy'),
  })
```

2023-03-09 04:10 UTC, piro0919 commented on src/app/page.tsx
> +                  <time>{createdAt}</time>
[nits]

こんなタグありましたっけ？ 👀

2023-03-09 04:10 UTC, piro0919 commented on src/app/page.tsx
> +                      <div key={index}>{fields.title}</div>
[must]

key に index は避けましょうー。

2023-03-09 04:10 UTC, piro0919 commented on src/app/page.tsx
> +                    {category?.map(({ fields }, index) => (
[must]

title まで展開しちゃいましょう。

2023-03-09 04:10 UTC, piro0919 commented on src/app/page.tsx
> +}
[imo]

一旦この書き方でも問題ないですが、これだとサーバー側にキャッシュが作成されないのがもったいないですね。
後ほど fetch  を使用した書きっぷりに変えたほうが良い気もしますね。 👍

2023-03-09 04:10 UTC, piro0919 commented on src/app/page.tsx
>  import styles from '../styles/Home.module.css'
[imo]

スコープ外ですが、ファイルの配置場所が悪いので同ディレクトリ内に移動させちゃいましょう。

2023-03-09 15:51 UTC, yanachuwan9sm commented on src/app/page.tsx
> +  //* MEMO: 子コンポーネントにPropsを渡す際は、postDateを渡す
> @yanachuwan9sm
> 
> [f21dbc4](https://github.com/yanachuwan9sm/own-fm/pull/69/commits/f21dbc4c6fd060e6c2582589e802c705d1dacf7b) このコミット良くないですね。 🙅‍♂️ あとから振り返ったときにコミットの内容がすぐに理解できるような粒度かつコミットメッセージを打つように心がけましょうー。

確かに、このコミットメッセージと粒度だと、
数ヶ月後に振り返った時にレビューコメントに対する何の修正を行ったのかが分かりづらいですね...
コミットの粒度、また作業内容が伝わるコミットメッセージ意識します🙇‍♂️

2023-03-09 15:51 UTC, yanachuwan9sm commented
> @yanachuwan9sm
> 
> [f21dbc4](https://github.com/yanachuwan9sm/own-fm/pull/69/commits/f21dbc4c6fd060e6c2582589e802c705d1dacf7b) このコミット良くないですね。 🙅‍♂️ あとから振り返ったときにコミットの内容がすぐに理解できるような粒度かつコミットメッセージを打つように心がけましょうー。

確かに、このコミットメッセージと粒度だと、
数ヶ月後に振り返った時にレビューコメントに対する何の修正を行ったのかが分かりづらいですね...
コミットの粒度、また作業内容が伝わるコミットメッセージ意識します🙇‍♂️

2023-03-09 16:17 UTC, yanachuwan9sm commented on src/app/page.tsx
> +                  <time>{createdAt}</time>
[web.dev](https://web.dev/blog/)にて、日時を表す文字列を`time`タグで使用していた事と、
Google検索結果のスニペットに日付を表示することができる事から日付を囲むタグに`time`を採用しましたmm

2023-03-09 16:32 UTC, yanachuwan9sm commented on src/app/page.tsx
> +}
@piro0919 
> 一旦この書き方でも問題ないですが、これだとサーバー側にキャッシュが作成されないのがもったいないですね。


 `app`ディレクトリ上で動作する`fetch()`使っていく感じって事ですかね、、？👀
(まだ記事が少ない & まだ完全に読めていないので、あんまり知識ないですが)

https://beta.nextjs.org/docs/data-fetching/caching

2023-03-11 09:57 UTC, yanachuwan9sm commented on src/libs/contentful.ts
> +export const getBlogPosts = async (): Promise<
@piro0919 
>汎用的なファイルを作るくらいなら、1 つ 1 つのファイルを厳密にしたほうが、結果的に保守性は高くなるかなと。

有難うございますmm
その方向性で行きます👍

2023-03-11 09:59 UTC, yanachuwan9sm commented on src/app/page.tsx
> +  })
イマイチどころか、かなりBADですね、、、
以下にて修正致しました！

0ef44c68a73dabf6a0cd7aadf6d67ba4be7366df

2023-03-11 10:00 UTC, yanachuwan9sm commented on src/app/page.tsx
> +  //* MEMO: 子コンポーネントにPropsを渡す際は、postDateを渡す
@piro0919 

そうですね！適当に残したコメントが差分出てましたmm
以下にて不要なコメント削除しました！

37f3ac3f6d792dd8a049acf298c9586f7e8217cd

2023-03-11 10:01 UTC, yanachuwan9sm commented on src/app/page.tsx
> +                      <div key={index}>{fields.title}</div>
思いっきりここもBADな書き方してました、、、
以下のコミットにて、li要素のkeyを一意性のあるユーニクな値に変更しています！

a90ef5a97106e51a33f51d9e84736ed1ecffd157

2023-03-11 10:02 UTC, yanachuwan9sm commented on src/app/page.tsx
>  import styles from '../styles/Home.module.css'
以下にてcssファイルを同ディレクトリ内に移動しましたmm

a8a015b640b9a095165fee19468bfb3ca1149b2c

2023-03-11 10:04 UTC, yanachuwan9sm commented on src/app/page.tsx
> +                    {category?.map(({ fields }, index) => (
以下にて、 `id`及び`title`展開の作業しておりますmm

a90ef5a97106e51a33f51d9e84736ed1ecffd157

2023-03-11 11:53 UTC, piro0919 requested changes
もう少し頑張りましょうー。 👍

2023-03-11 11:53 UTC, piro0919 commented on src/app/page.tsx
> +  })
[imo]

まだ綺麗に書けますね。

```ts
  const postList = postDate.items.map(({sys: { id, createdAt, updatedAt }}) => ({
    ...item.fields,
    id,
    createdAt: format(new Date(createdAt), 'MMM dd, yyyy'),
    updatedAt: format(new Date(updatedAt), 'MMM dd, yyyy'),
  })
```

2023-03-12 06:25 UTC, yanachuwan9sm commented on src/app/page.tsx
> +  })
本当ですね、、ここもスマートに書き換えました👍
ご確認頂き有難うございます！！

67bbe55e39c0d9bcac5db4d37b928868ae241b70

2023-03-12 06:48 UTC, piro0919 requested changes

2023-03-12 06:48 UTC, piro0919 commented on src/app/page.tsx
> +    }
[imo]

まだ綺麗に書けますね。

  const postList = postDate.items.map(({sys: { id, createdAt, updatedAt }}) => ({
    ...item.fields,
    id,
    createdAt: format(new Date(createdAt), 'MMM dd, yyyy'),
    updatedAt: format(new Date(updatedAt), 'MMM dd, yyyy'),
  })

2023-03-14 14:30 UTC, yanachuwan9sm commented on src/app/page.tsx
> +    }
ぬお、、確かにですmm
こちらのコミットにて修正しております！

b12583a8529e41a944791f50fd573419bd0e793a

2023-03-14 15:10 UTC, piro0919 approved these changes
LGTM 👍

2023-03-14 15:47 UTC, yanachuwan9sm commented
thank you for approval👍

2023-03-14 15:48 UTC, merged