feat: :sparkles: add blog detail page
yanachuwan9sm/own-fm pull request #81
Opened 2023-03-23 09:44 UTC by yanachuwan9sm

close #76

2023-03-23 13:25 UTC, piro0919 requested changes

2023-03-23 13:25 UTC, piro0919 commented on src/app/blog/[slug]/page.tsx
> +  return [...paths]
[nits]

空行ほしいですね。

2023-03-23 13:25 UTC, piro0919 commented on src/app/blog/[slug]/page.tsx
> +  return [...paths]
[imo]

`return paths` で良いような？
公式の書き方がこんな感じでした？ 👀

2023-03-23 13:25 UTC, piro0919 commented on src/app/blog/[slug]/page.tsx
> +const getBlogPosts = async (): Promise<
[imo]

定数に切り出すメリットもないように見えますね。 👀

2023-03-23 13:25 UTC, piro0919 commented on src/app/blog/[slug]/page.tsx
> +  const postData = await client.getEntries<Contentful.IBlogPostFields>({
[must]

`getEntry` ってありませんでしたっけ？ 🐱

2023-03-23 13:25 UTC, piro0919 commented on src/app/blog/[slug]/page.tsx
> +  }
[imo]

return で返すのは `postData` のほうが好ましいかなと。
基本的に api のレスポンスはそのまま返して、page container 側で加工したほうが保守性は高いと思います。 👍

2023-03-23 13:25 UTC, piro0919 commented on src/app/blog/[slug]/page.tsx
> +type blogPostType = {
[must]

型は upper で書きましょう。 🙅‍♂️

2023-03-23 13:25 UTC, piro0919 commented on src/app/blog/[slug]/page.tsx
> +import serializeMDX from 'libs/compile'
[nits]

import する名前がファイル名とズレているのは個人的には好きじゃないですね。

2023-03-26 01:39 UTC, yanachuwan9sm commented
別のPRになりますが、以下のコメントを頂きましたのでこちらのPRで、
`next-mdx-remote`のインストールを行いました。
https://github.com/yanachuwan9sm/own-fm/pull/80#pullrequestreview-1354609577

45c982622236d69f589014a9bc2a9e551affffe0

2023-03-26 01:40 UTC, yanachuwan9sm commented on src/app/blog/[slug]/page.tsx
> +import serializeMDX from 'libs/compile'
ご指摘有難う御座います〜👍
以下にて修正しましたので、ご確認お願いします！

bcb77a66f8306536690cc14d02f2d4b78de7ed12

2023-03-26 01:41 UTC, yanachuwan9sm commented on src/app/blog/[slug]/page.tsx
> +type blogPostType = {
`getEtnrys`メソッドを`getEntry`メソッドに変更するにあたり、
こちらの型は不要になったので削除しましたmm

969814ada2bfd0cd012e659885113aca29d9aa59

2023-03-26 01:50 UTC, yanachuwan9sm commented on src/app/blog/[slug]/page.tsx
> +  }
有難う御座います！
以下のcommitにて修正致しました👍

969814ada2bfd0cd012e659885113aca29d9aa59

2023-03-26 01:52 UTC, yanachuwan9sm commented on src/app/blog/[slug]/page.tsx
> +  const postData = await client.getEntries<Contentful.IBlogPostFields>({
`getEntry`メソッドありました、、見落としておりました😵

969814ada2bfd0cd012e659885113aca29d9aa59

2023-03-26 01:55 UTC, yanachuwan9sm commented on src/app/blog/[slug]/page.tsx
> +const getBlogPosts = async (): Promise<
`getEtnry`メソッドに書き換え、apiのレスポンスをそのまま返却する形に修正しました。


bf9fcbebec76aa7bd289c0070f2f71a77d94856a

2023-03-26 01:56 UTC, yanachuwan9sm commented on src/app/blog/[slug]/page.tsx
> +  return [...paths]
公式Docsを確認した所、
自分が実装したような記述( `return [...pahts]`)は見当たらなかったため、修正致しました！

9740969b1880a62f94732e0f02bc31e729dbfab0

2023-03-26 01:57 UTC, yanachuwan9sm commented on src/app/blog/[slug]/page.tsx
> +  return [...paths]
こちら修正しました！

9740969b1880a62f94732e0f02bc31e729dbfab0

2023-04-07 17:01 UTC, piro0919 approved these changes
LGTM 👍

2023-04-07 17:01 UTC, piro0919 commented on src/libs/mdx-remote-option.ts
> +export default mdxRemoteOption
[imo]

ファイル名は kebab じゃなくて camel のほうが好みではありますが、統一性さえ保てれば良いかなと。

2023-04-07 17:05 UTC, yanachuwan9sm commented
thank you for approving!

2023-04-07 17:06 UTC, merged