feat(plugin): :sparkles: convert images included in markdown to next/image
yanachuwan9sm/own-fm pull request #95
Opened 2023-04-10 16:02 UTC by yanachuwan9sm

close #94

2023-04-10 16:11 UTC, yanachuwan9sm commented
[申し送り]
今回はmarkdownの画像がnext/imageに変換されることだけ確認したいので、
CSSはインラインで書いてます。

2023-04-10 16:15 UTC, yanachuwan9sm commented
プレースホルダーも動作していること確認しましたmm
(キャッシュ無効化 & 高速3Gにて検証)
https://user-images.githubusercontent.com/95360878/230943628-c288fe67-8c9f-4d00-b887-9e2f8cd2b5af.mov

2023-04-10 16:38 UTC, piro0919 requested changes
全体的に linter が弱いのが気になりつつ。

2023-04-10 16:38 UTC, piro0919 commented on src/components/NextFigureImage/index.tsx
> +}
[imo]

`alt` と `blurDataURL` と `src` の定義がダブってるような。 👀 
以下で十分ですね。

```tsx
type NextFigureImageProps = Omit<
  ImageProps,
  'src' | 'width' | 'height' | 'blurDataURL' | 'alt'
> & {
  aspectRatio: string
}
```

2023-04-10 16:38 UTC, piro0919 commented on src/components/NextFigureImage/index.tsx
> +type NextFigureImageProps = Omit<
[must]

props の型には export をつけましょうー。

2023-04-10 16:38 UTC, piro0919 commented on src/libs/rehype-image-optimum.ts
> +        typeof node.properties.src === 'string'
[imo]

まとめれますね。

`typeof node?.properties?.src === 'string'`

2023-04-10 16:38 UTC, piro0919 commented on src/libs/rehype-image-optimum.ts
> +    visit(tree, 'element', visitor)
[must]

わざわざ visit 関数を切り出す必要もないような…？
matches はもっと綺麗に作成できると思いますよー。

2023-04-10 16:38 UTC, piro0919 commented on src/libs/rehype-image-optimum.ts
> +  return async (tree: Node, _file: VFileCompatible) => {
[imo]

ワンライナーでー。

2023-04-10 16:38 UTC, piro0919 commented on src/components/NextFigureImage/index.tsx
> +  return (
[imo]

ワンライナーでー。

2023-04-10 16:38 UTC, piro0919 commented on src/components/MdxContent/index.tsx
> +      components={{ ...MdxComponents, ...(components || {}) }}
[imo]

スコープ外含みますが、options と components は引数で受け取る段階でデフォルト値を与えた方が良い気がしますね。

2023-04-10 16:38 UTC, piro0919 commented on src/components/MdxComponents/index.tsx
> +export default MdxComponents
[must]

なんかすごい謎な実装ですね。 👀 
エビデンスあればほしいですー。

2023-04-11 00:51 UTC, yanachuwan9sm commented on src/components/NextFigureImage/index.tsx
> +type NextFigureImageProps = Omit<
`NextFigureImageProps` を export していない意図として、
`export default` で統一させるために、
以下のような形で`NextFigureImageProps`をインポートする形にしたのですが、
修正した方が良いのでしょうか？

```tsx
type NextFigureImageProps = React.ComponentProps<typeof NextFigureImage>
```

2023-04-11 01:59 UTC, piro0919 commented on src/components/NextFigureImage/index.tsx
> +type NextFigureImageProps = Omit<
@yanachuwan9sm 

返信の内容がちょっと理解できず…。 🙇 

コンポーネントファイルは以下の設計が良いと思っていますが、どうでしょうか？

- ファイルに対応するコンポーネント：default export
- ファイルに対応するコンポーネントの props の型：named export

質問がありましたら引き続き聞いていただければと。

2023-04-11 12:57 UTC, yanachuwan9sm commented on src/components/NextFigureImage/index.tsx
> +type NextFigureImageProps = Omit<
@piro0919 
なるほどです！
てっきり default export で統一 するため、 named export を一切使わないのかと思いました、、！

2023-04-11 13:19 UTC, piro0919 commented on src/components/NextFigureImage/index.tsx
> +}
@yanachuwan9sm 

あ 逆でしたね、申し訳ないです。 🙇

2023-04-11 17:48 UTC, piro0919 commented on src/components/MdxComponents/index.tsx
> +export default MdxComponents
@yanachuwan9sm 

ちょっと手元で確認してみますので、しばしお待ちをば…。

2023-04-13 14:12 UTC, yanachuwan9sm commented on src/components/MdxComponents/index.tsx
> +export default MdxComponents
@piro0919 

piroさんのコードを参考に、こちらにて修正致しました！
(ここって、imgタグの型に合うように、NextFigureImageコンポーネントの型を修正させた感じであってますかね？
違ったらお時間ある時教えてくださいmm)

ea896ba5c2a1b74b12177534ad9dba96752cd2f0

ea896ba5c2a1b74b12177534ad9dba96752cd2f0

2023-04-13 14:13 UTC, yanachuwan9sm commented on src/components/MdxContent/index.tsx
> +      components={{ ...MdxComponents, ...(components || {}) }}
以下のコミットにて修正しております🙇‍♂️

c1bf4fd3620b8e2369d587d2e43c451723798f29

2023-04-13 14:14 UTC, yanachuwan9sm commented on src/libs/rehype-image-optimum.ts
> +  return async (tree: Node, _file: VFileCompatible) => {
以下にて修正対応しました！

10add7590af1631dc1f975b9316a676762577232

2023-04-13 14:15 UTC, yanachuwan9sm commented on src/libs/rehype-image-optimum.ts
> +    visit(tree, 'element', visitor)
visit関数を切り出さずに書き直してみました！

10add7590af1631dc1f975b9316a676762577232

2023-04-13 14:16 UTC, yanachuwan9sm commented on src/components/NextFigureImage/index.tsx
> +}
こちら、piroさんにリファクタリング頂いたものを参考に修正加えました〜

ce5247c7999ca09d876243ea22d9b05e56ebeddf

2023-04-13 14:16 UTC, yanachuwan9sm commented on src/components/NextFigureImage/index.tsx
> +type NextFigureImageProps = Omit<
以下にて修正対応しております🙇‍♂️

ce5247c7999ca09d876243ea22d9b05e56ebeddf

2023-04-13 20:36 UTC, piro0919 commented on src/components/MdxComponents/index.tsx
> +export default MdxComponents
@yanachuwan9sm 

認識は合ってますが、これ型的に合ってるんですかね？

2023-04-13 20:37 UTC, piro0919 approved these changes
一旦通しちゃいますが、コンポーネント設計含め色々と破綻している部分が出てきてますね。
あと linter が弱いのがかなり気になりますねー。

2023-04-15 14:32 UTC, merged